sonar.projectKey=hshinosa_Devops-Berra
sonar.organization=hshino
sonar.projectName=ApliKasir-Website

sonar.sources=app,resources/js
sonar.tests=tests,resources/js
sonar.exclusions=vendor/**,node_modules/**,public/build/**,storage/**,bootstrap/cache/**,**/*.test.jsx,**/*.spec.jsx

sonar.php.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=coverage-js/lcov.info

sonar.sourceEncoding=UTF-8
