sonar.projectKey=ApliKasir-Codebase_ApliKasir-Website
sonar.organization=hshino
sonar.projectName=ApliKasir-Website

sonar.sources=app,resources/js
sonar.tests=tests
sonar.exclusions=vendor/**,node_modules/**,public/build/**,storage/**,bootstrap/cache/**

sonar.php.coverage.reportPaths=coverage.xml

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
